language: node_js
node_js: 
  - "lts/*"
before_script:
  - npm run coverage
  - npm run lint
script:
  - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: ./out
  on:
    branch: master