language: node_js
node_js: 
  - "lts/*"
before_script:
  - npm run coverage
  - npm run lint
script:
  - npm run build
  - cd examples/basic/ && npm run build
before_deploy:
  - npm run create-documentation
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: ./docs
  on:
    branch: master