language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - "lts/*"
install:
  - npm install -g codecov
  - npm install
before_script:
  - npm run check
  - cd examples/basic/ && npm install && cd ../..
script:
  - npm run build
  - cd examples/basic/ && npm run build && cd ../..
  - npx istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec
  - codecov
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
before_deploy:
  - npm run create-documentation
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: ./docs
  on:
    branch: master
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
